# Generated by Django 4.1.1 on 2022-10-02 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('contrasenia', models.CharField(max_length=50)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('alta_usuario', models.CharField(max_length=45)),
                ('alta_fecha', models.DateTimeField(auto_now_add=True)),
                ('modif_usuario', models.CharField(max_length=45)),
                ('modif_fecha', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
